version: "3"

services:
    Attacker:
        image: handsonsecurity/seed-ubuntu:large
        container_name: Attacker-10.9.0.2
        tty: true
        cap_add:
            - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2
        volumes:
            - ./volumes:/volumes
        command: bash -c "
                      /etc/init.d/openbsd-inetd start &&
                      apt update && apt upgrade -y &&
                      apt install -y make gcc &&
                      apt-get install -y libpcap-dev libnet-dev &&
                      pip3 install numpy matplotlib scapy &&
                      iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP &&
                      tail -f /dev/null
                 "

    Monitor:
        image: handsonsecurity/seed-ubuntu:large
        container_name: Monitor-10.9.0.3
        tty: true
        cap_add:
            - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.3
        volumes:
            - ./volumes:/volumes
        command: bash -c "
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

    ApacheServer:
        image: httpd:latest
        container_name: ApacheServer-10.9.0.4
        cap_add:
            - ALL
        privileged: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.4
        ports:
            - "80:80"
        

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
